### ISSUE TITLE
Duplicate activity names now generates error resulting in skipping of all test scenarios

### ISSUE THREAD

**Issue by jwetter** [nexiality/nexial-core#10]
Latest version of 2.9 has the following error being generated:

» Error:          Error found in [simplifyOnboardingAPI-plan.002,simplifyOnboarding.20200106_145752.001.xlsx][SF_API-createRecordAccount][A22]: Found duplicate activity name 'Log Event ID information'
org.nexial.commons.InvalidInputRuntimeException: Error found in [simplifyOnboardingAPI-plan.002,simplifyOnboarding.20200106_145752.001.xlsx][SF_API-createRecordAccount][A22]: Found duplicate activity name 'Log Event ID information'
        at org.nexial.core.model.TestScenario.parse(TestScenario.java:252)
        at org.nexial.core.model.TestScenario.<init>(TestScenario.java:69)
        at org.nexial.core.model.ExecutionContext.parse(ExecutionContext.java:1883)
        at org.nexial.core.model.ExecutionContext.useTestScript(ExecutionContext.java:314)
        at org.nexial.core.ExecutionThread.run(ExecutionThread.java:175)

Duplicate activity names should not be generating errors as this was not called out in Release Notes and version 2.7 is working without issue.

**Comment by mikeliucc** [comment]
Josh, there's a simple solution to this issue:
1) Please update to a recent Nexial build (anything after #739 should be fine)
2) Please run `bin/nexial-script-update.cmd` with the `-u` flag, like this:
```
cd C:\projects\nexial-core\bin
nexial-script-update.cmd -v -t C:\projects\MY_PROJECT\artifact\script -u
```
3) This script will automatically fix all duplicate activity names by adding a number to the end of it

Activity names need to be unique for accurate tallies in the execution report. Please let me know if this fixes your issue. Thanks!

**Comment by mikeliucc** [comment]
For more info, please visit https://nexiality.github.io/documentation/userguide/BatchFiles#nexial-script-update

Thanks.
