### ISSUE TITLE
grpahql documentation missing

### ISSUE THREAD

**Issue by desaihemal** [nexiality/nexial-core#14]
### Subject of the issue

Missing documentation. https://nexiality.github.io/documentation/commands/ws/#available-commands doesn't have details about `gaphql` command. 
### Your environment Details

* Nexial Version:  nexial-core dev_1394
* Java(jdk) Version: 17.0.1
* Operating System:  x86_64 Mac OS X 11.6
* Browser Version (if applicable):

**Comment by mikeliucc** [comment]
Thanks, @desaihemal, for reporting this. This issue has been fixed.
