### ISSUE TITLE
GraphQL call fails

### ISSUE THREAD

**Issue by desaihemal** [nexiality/nexial-core#15]
### Subject of the issue

ws.graphql command fails with `IllegalArgumentException: Invalid GraphQL operation found: {"query":"query` error even though the query is valid.

### Your environment Details

* Nexial Version: nexial-core dev_1394
* Java(jdk) Version: 1.17.0
* Operating System:  Mac OS X 11.6
* Browser Version (if applicable): 

### Steps to reproduce
 Tell us how to reproduce this issue.
 - Setup test script for Graphql with ws.graphql command 
 -  end point url - https://countries.trevorblades.com/
 - Payload `query {
  country(code: "BR") {
    name
    native
    capital
    emoji
    currency
    languages {
      code
      name
    }
  }
}`
 - Run the script

**Comment by mikeliucc** [comment]
Thanks for reporting this issue, @desaihemal 
This indeed was an issue -- strangely enough, it did not surface for other GQ sites... ¯\(°_o)/¯

Anyways, I've fixed this issue from Nexial's source and is available for your use now via [#1396](https://github.com/nexiality/nexial-core/releases/tag/nexial-core-v4.3_1396). Please give that a try and report back your findings when you can. Thank you!

**Comment by mikeliucc** [comment]
and... just as a way of showing what the fix would result in, here's my test script:
![image](https://user-images.githubusercontent.com/8107782/142329478-6a5b66da-4d10-4e6c-9a91-49bbd78971e5.png)

and the result:
![image](https://user-images.githubusercontent.com/8107782/142331123-cb90ea5f-94af-4f75-aed8-14b6e7504ca8.png)

I will close this ticket upon your confirmation. Thanks!

**Comment by mikeliucc** [comment]
@desaihemal any updates on this issue? Can you give the latest Nexial release a try?

Thanks much, automike

**Comment by desaihemal** [comment]
Hey Sorry,
I did verify the change. It’s working now.

**Comment by mikeliucc** [comment]
Thanks @desaihemal . Closing this issue now :-)
