### ISSUE TITLE
set to turn off shell trace drops java exit value

### ISSUE THREAD

**Issue by bbacker** [nexiality/nexial-core#5]
### Your environment Details

* Nexial Version: 
* Java(jdk) Version:
* Operating System: 
* Browser Version (if applicable): 

### Expected behavior
nexial.sh should exit with non zero exit code on java error like invalid arguments

### Actual behaviour
exits with 0 because line 'set +x' always exits with 0

**Comment by mikeliucc** [comment]
Thanks @bbacker ! Great PR, which is now merged. Appreciate the collaboration.

I'll be doing the same for nexial.cmd for Windows execution as well.

**Comment by mikeliucc** [comment]
@bbacker can you please confirm that the PR merge fixes this issue?  Thanks!

**Comment by bbacker** [comment]
looks great - thanks for quickly adding this
