### ISSUE TITLE
After each test scenario the console shows a Null Pointer error

### ISSUE THREAD

**Issue by Sheck-work** [nexiality/nexial-core#8]
**Is your feature request related to a problem? Please describe.**
I noticed that after each "thread" summary, which amounts to each scenario execution, including iterations of a scenario, there is a Null Pointer exception:

Exception in thread "Thread-1" java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:460)
        at java.util.Properties.setProperty(Properties.java:166)
        at java.lang.System.setProperty(System.java:796)
        at org.nexial.core.ExecutionThread.run(ExecutionThread.java:230)

**Describe the solution you'd like**
The tests still execute correctly, so I don't see any immediate effects. But I figured its not a clean execution if there is a Null Pointer.

**Describe alternatives you've considered**
No alternative.

**Additional context**
![request-fixnullpointer](https://user-images.githubusercontent.com/41490600/43296441-3eca4838-9100-11e8-8a34-0c442cc2a28a.png)

**Comment by akshay2409** [comment]
@Sheck-work Can you please mention Nexial version you are using in the issue? I doubt that you have an old Nexial version. Please try with the latest release. If still, you are getting the error, please let us know. Thanks.

**Comment by Sheck-work** [comment]
Sorry I forgot the Nexial version. I rushed the issue entry.
Regardless, your suggestion worked. I updated to the latest and the Null Pointer is no longer present.
